/**
 * Step 27: Taxonomy for keyword extraction, aliases, and stopwords (EN/TR)
 */

/** English stopwords */
export const STOPWORDS_EN = [
  'and',
  'or',
  'the',
  'a',
  'an',
  'to',
  'for',
  'of',
  'in',
  'on',
  'with',
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'being',
  'have',
  'has',
  'had',
  'do',
  'does',
  'did',
  'will',
  'would',
  'should',
  'could',
  'may',
  'might',
  'must',
  'can',
  'this',
  'that',
  'these',
  'those',
  'at',
  'by',
  'from',
  'up',
  'about',
  'into',
  'through',
  'during',
  'before',
  'after',
  'above',
  'below',
  'between',
  'under',
  'again',
  'further',
  'then',
  'once',
]

/** Turkish stopwords */
export const STOPWORDS_TR = [
  've',
  'ile',
  'bir',
  'için',
  'de',
  'da',
  'ya',
  'veya',
  'bu',
  'şu',
  'o',
  'olan',
  'olarak',
  'var',
  'yok',
  'ki',
  'mi',
  'mı',
  'mu',
  'mü',
  'ise',
  'gibi',
  'kadar',
  'daha',
  'en',
  'çok',
  'az',
  'her',
  'bazı',
  'tüm',
  'bütün',
  'şey',
]

/** English skill keyword aliases (canonical -> variations) */
export const SKILL_ALIASES_EN: Record<string, string[]> = {
  react: ['reactjs', 'react.js', 'react-js'],
  node: ['nodejs', 'node.js', 'node-js'],
  typescript: ['ts'],
  javascript: ['js', 'ecmascript'],
  python: ['py'],
  'project management': ['pm', 'scrum', 'kanban', 'agile'],
  kubernetes: ['k8s'],
  docker: ['containerization'],
  aws: ['amazon web services'],
  gcp: ['google cloud platform'],
  azure: ['microsoft azure'],
  ci: ['continuous integration', 'cicd', 'ci/cd'],
  sql: ['structured query language', 'mysql', 'postgresql', 'postgres'],
  nosql: ['mongodb', 'cassandra', 'dynamodb'],
  git: ['github', 'gitlab', 'bitbucket'],
  rest: ['restful', 'rest api'],
  graphql: ['gql'],
  'machine learning': ['ml', 'ai', 'artificial intelligence'],
}

/** Turkish skill keyword aliases */
export const SKILL_ALIASES_TR: Record<string, string[]> = {
  'proje yönetimi': ['scrum', 'kanban', 'çevik'],
  pazarlama: ['marketing', 'dijital pazarlama'],
  react: ['reactjs', 'react.js'],
  node: ['nodejs', 'node.js'],
  typescript: ['ts'],
  javascript: ['js'],
  python: ['py'],
  veri: ['data', 'veri tabanı'],
}

/** English role keywords (common job titles/specializations) */
export const ROLE_KEYWORDS_EN = [
  'product manager',
  'frontend',
  'backend',
  'full stack',
  'fullstack',
  'data analyst',
  'data scientist',
  'marketing manager',
  'designer',
  'ux designer',
  'ui designer',
  'devops',
  'software engineer',
  'qa engineer',
  'test engineer',
  'scrum master',
  'project manager',
  'tech lead',
  'engineering manager',
]

/** Turkish role keywords */
export const ROLE_KEYWORDS_TR = [
  'ürün yöneticisi',
  'önyüz',
  'arkayüz',
  'tam yığın',
  'veri analisti',
  'veri bilimcisi',
  'pazarlama yöneticisi',
  'tasarımcı',
  'yazılım mühendisi',
  'test mühendisi',
  'scrum master',
  'proje yöneticisi',
]
